#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements

sudo cp /etc/hosts /etc/hosts.bak

{
    sed 's/127.0.0.1/127.0.0.2/g' /etc/hosts

    echo "8.8.8.8 facebook.com"
} | sudo tee /etc/hosts > /dev/null
